-- Ödeme modülünün denetim izi: para hareketi veya borç değiştiren eylemler.
ALTER TYPE "AuditAction" ADD VALUE 'PAYMENT_COLLECTED';
ALTER TYPE "AuditAction" ADD VALUE 'PAYMENT_VOIDED';
ALTER TYPE "AuditAction" ADD VALUE 'INSTALLMENT_PLAN_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'INSTALLMENT_POSTPONED';
ALTER TYPE "AuditAction" ADD VALUE 'INSTALLMENT_RESTRUCTURED';
ALTER TYPE "AuditAction" ADD VALUE 'ENROLLMENT_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE 'DISCOUNT_GRANTED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPENSE_PAID';
ALTER TYPE "AuditAction" ADD VALUE 'ACCOUNT_TRANSFERRED';
ALTER TYPE "AuditAction" ADD VALUE 'PAYROLL_PAID';
